### ISSUE TITLE
no new blocks

### ISSUE THREAD

**Issue by hughht5** [ethereum/guide#2]
@gavofyork running on one node I can't get new blocks to generate. 

Any ideas what I've done wrong?

Coinbase:
web3.eth.coinbase = '0x2b88c7c88c32a39890ac49b2be7f481277c0b0f9'

config:
`{
    "sealEngine": "BasicAuthority",
    "options": {
        "authorities": [
            "0x2b88c7c88c32a39890ac49b2be7f481277c0b0f9"
        ]
    },
    "params": {
        "accountStartNonce": "0x",
        "maximumExtraDataSize": "0x1000000",
        "blockReward": "0x",
        "registrar": "",
        "networkID" : "0x45"
    },
    "genesis": {
        "author": "0x0000000000000000000000000000000000000000",
        "timestamp": "0x00",
        "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "extraData": "0x",
        "gasLimit": "0x1000000000000"
    },
    "accounts": {
        "0000000000000000000000000000000000000001": { "wei": "1", "precompiled": { "name": "ecrecover", "linear": { "base": 3000, "word": 0 } } },
        "0000000000000000000000000000000000000002": { "wei": "1", "precompiled": { "name": "sha256", "linear": { "base": 60, "word": 12 } } },
        "0000000000000000000000000000000000000003": { "wei": "1", "precompiled": { "name": "ripemd160", "linear": { "base": 600, "word": 120 } } },
        "0000000000000000000000000000000000000004": { "wei": "1", "precompiled": { "name": "identity", "linear": { "base": 15, "word": 3 } } }
    },
    "network": {
        "nodes": [
            "enode://45c1e7938feb974906e9db17f083398475e61464f1542fed2d07d6c564c164eca488ed627fff79b5fa243d108031add09f2faa51c35ce9ff68b55f33c29b973c@127.0.0.1:40404",
            "enode://e88d8c664b8e1228c91f318e6da3ce1d7e47907f6f36e3a73cd53de9a21c085a62b9c490f2446b1d4ea0be7187064f5b366b262fcd03ca90660602da48a82b85@168.62.233.254:40404"
        ]
    }
}

`

**Comment by bobsummerwill** [comment]
Hey @hughht5!
This repo is the guide for TurboEthereum for Frontier, not for anything active, so I'll close this ticket.
Depending on what client you are using, you likely want to log a ticket against either http://github.com/ethereum/go-ethereum or http://github.com/ethereum/webthree-umbrella.  Thanks!
